[profile.default]
solc-version = '0.8.26'
evm_version = 'cancun'
src = 'contracts'
out = 'out'
test = 'test/foundry'
cache_path = 'cache/foundry'
verbosity = 3
libs = ["node_modules", "lib"]

remappings = [
    # Due to a misconfiguration of solidity-bytes-utils, an outdated version
    # of forge-std is being dragged in
    # 
    # To remedy this, we'll remap the ds-test and forge-std imports to ou own versions
    'ds-test/=node_modules/@layerzerolabs/toolbox-foundry/lib/ds-test',
    'forge-std/=node_modules/@layerzerolabs/toolbox-foundry/lib/forge-std',
    '@layerzerolabs/=node_modules/@layerzerolabs/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'v4-periphery/=lib/v4-periphery/',
    'v4-core/=lib/v4-core/',
    '@pythnetwork/pyth-sdk-solidity/=node_modules/@pythnetwork/pyth-sdk-solidity',
    '@layerzerolabs/=node_modules/@layerzerolabs/',
]

[fuzz]
runs = 1000
